import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Amplify, Auth } from 'aws-amplify';
import { withAuthenticator, Button, Heading } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import awsconfig from '../src/aws-exports';


// Amplify.configure(awsconfig);
Amplify.configure({ ...awsconfig, ssr: true });

function Home({ signOut, user }) {


Auth.currentSession().then(data => console.log(data)).catch(err => console.log(err));
Auth.currentAuthenticatedUser({bypassCache: false  // Optional, By default is false. If set to true, this call will send a request to Cognito to get the latest user data
}).then(user => console.log(user))
.catch(err => console.log(err));

  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Cognito Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
   
    Basic Cognito Next js ISR app
      <h1>Hello {user.username}</h1>
      <button onClick={signOut}>Sign out</button>
    </>
  )
}

export default withAuthenticator(Home);

